- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/values.yaml
> [fluentd-elasticsearch] update fluentd-es image to 3.0.5

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
Signed-off-by: André Bauer <andre.bauer@bike24.net>
* updates fluentd image which supports xpack
- fixes https://github.com/kokuwaio/helm-charts/issues/13
> [fluentd-elasticsearch] updated fluent docker image

- .github/workflows/ci.yaml
- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/templates/_helpers.tpl
- charts/fluentd-elasticsearch/templates/clusterrole.yaml
- charts/fluentd-elasticsearch/templates/clusterrolebinding.yaml
- charts/fluentd-elasticsearch/templates/configmaps.yaml
- charts/fluentd-elasticsearch/templates/daemonset.yaml
- charts/fluentd-elasticsearch/templates/metrics-service.yaml
- charts/fluentd-elasticsearch/templates/pod-security-policy.yaml
- charts/fluentd-elasticsearch/templates/prometheusrule.yaml
- charts/fluentd-elasticsearch/templates/role.yaml
- charts/fluentd-elasticsearch/templates/rolebinding.yaml
- charts/fluentd-elasticsearch/templates/service-account.yaml
- charts/fluentd-elasticsearch/templates/service.yaml
- charts/fluentd-elasticsearch/templates/servicemonitor.yaml
* updates helm requirement to 3.0.0
* updates k8s requirement to 1.16.0
* fixes https://github.com/kokuwaio/helm-charts/issues/21
> [flunetd-elasticsearch] updated chart requirements - helm to 3.0.0 and k8s to 1.16.0

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/templates/service.yaml
* fixes usage of service
- fixes # https://github.com/kokuwaio/helm-charts/issues/23
> [fluentd-elasticsearch] fix service

- .github/workflows/ci.yaml
> added codespell to ci

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/templates/configmaps.yaml
- charts/fluentd-elasticsearch/templates/daemonset.yaml
- charts/fluentd-elasticsearch/values.yaml
Signed-off-by: baczus <baczusc60@gmail.com>
PR adds new parameter _elasticsearch.template.overwrite_ to overwrite index template even if it already exists.
Ref docs: https://github.com/uken/fluent-plugin-elasticsearch#template_overwrite 
- fixes #
> Add parameter to overwrite index template

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/templates/configmaps.yaml
- charts/fluentd-elasticsearch/templates/daemonset.yaml
- charts/fluentd-elasticsearch/values.yaml
PR adds new parameter  _elasticsearch.buffer.chunkKeys_, which defines chunk keys in a buffer section. This change allows us to group events into chunks.
Fluentd documentation: https://docs.fluentd.org/configuration/buffer-section#chunk-keys
**Use case**
Use Kubernetes namespace as an index name. In that scenario the following parameters should be defined:
- _buffer.chunkKeys_ - set to _"tag, $.kubernetes.namespace_name"_
- _logstash.prefix_ set to _"logstash\_${$.kubernetes.namespace_name}\_"_
- fixes #
> Add parameter to group events into chunks

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
elasticsearch
fix a typo in README.md
fix a typo in README.md
- fixes #
> fix typo with README.md

- charts/mysqldump/Chart.yaml
- charts/mysqldump/README.md
- charts/mysqldump/templates/secret-mysql.yaml
- charts/mysqldump/values.yaml
* updated docker image & fixed exisitng secret
- fixes #39
> [mysqldump] updated docker image & fixed exisitng secret

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/templates/daemonset.yaml
Fixes a dumb typo :frowning_face:
> [fluentd-elasticsearch] Fix case typo

- charts/mysqldump/Chart.yaml
- charts/mysqldump/templates/_helpers.tpl
- fixes # https://github.com/kokuwaio/helm-charts/issues/55
> Fix for #55 - template "mysqldump.gcpsecretName" not defined

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/values.yaml
* fluentd-elasticsearch
update image
- fixes #
> [fluentd-elasticsearch] update fluentd elasticsearch image

- .github/workflows/release.yaml
- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/templates/daemonset.yaml
- charts/fluentd-elasticsearch/values.yaml
Allow auth password to be specified by existing secret
- fixes #61
> allow password to be referenced by secret

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/values.yaml
* fluentd-elasticsaerch
- fixes #88
> [fluentd-elasticsearch]update fluentd image

- .github/workflows/ci.yaml
- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/values.yaml
> [fluentd-elasticsearch] update fluent image to 3.4.0

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/templates/daemonset.yaml
- charts/fluentd-elasticsearch/values.yaml
Feature request: https://github.com/kokuwaio/helm-charts/issues/93
- none
> [fluentd-elasticsearch] Support for securityContext

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/templates/daemonset.yaml
- charts/fluentd-elasticsearch/values.yaml
[fluentd-elasticsearch] 
* update image 
* change image tag usage (uses appversion from chart.yaml by default)
- fixes #
> [fluentd-elasticsearch] update image & change image tag usage

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
* [vrt] make urls configurable
- fixes #
> [vrt] make urls configurable

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
> [vrt] fix resources

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/secrets.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
* remove es dependency
* set securitycontext for ui
- fixes #
> [vrt] remove es dependency

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/README.md
> [visual-regression-tracker] added vrt readme

- charts/mysqldump/Chart.yaml
- charts/mysqldump/README.md
- charts/mysqldump/templates/cron.yaml
mysqldump
Following warning occurs if you install the chart:
```bash
batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```
Update Cronjob API-Version to `batch/v1`. The new API-Version is available since Kubernetes v1.21, which leads to a breaking change of the helm chart (updated prequisites).
**Links**
- https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#cronjob-v1-batch
Tell me if anything needs to be changed.
> update CronJob apiVersion

- charts/fluentd-elasticsearch/Chart.yaml
> [fluentd-elasticsearch] update image to v4.2.0

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
* add topologySpreadConstraints
* update postgres dependency
* only add volumes when used
- fixes #
> [visual-regression-tracker] add topologySpreadConstraints

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/service-api.yaml
- charts/visual-regression-tracker/templates/service-ui.yaml
> [virtual regression tracker] add svc labels

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/pdb.yaml
- charts/visual-regression-tracker/values.yaml
> [vrt] add pdb

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/README.md
- charts/visual-regression-tracker/templates/NOTES.txt
- charts/visual-regression-tracker/templates/ingress-api.yaml
- charts/visual-regression-tracker/templates/ingress-ui.yaml
- charts/visual-regression-tracker/templates/service-api.yaml
- charts/visual-regression-tracker/templates/service-ui.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
* vrt
*  add podlabels
* change config 
* add default securitycontexts
* update postgres dependency
- fixes #
> [vrt] add podlabels / change config / add default securitycontexts

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yaml
- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
* vrt
* fix podLabels 
* make initContainer securityContext configurable
* raise livenessprobe failureThreshold to 10
* update ci
* update pr template
- fixes #
> [vrt] fix podLabels & initContainer securityContext

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/values.yaml
- visual regression tracker
- update
- fixes #
- .
> [visual regression tracker]

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/README.md
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
-  fix api & ui securitycontext config
- rename migration securitycontext var
- config broken
- fixes #
- .
> [vrt] fix securitycontext config

- charts/fluentd-elasticsearch/Chart.yaml
- fluentd-elasticsearch
- update docker image to v4.4.4
- fixes #
- .
> [fluentd-elasticsearch] - update image

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/README.md
- charts/visual-regression-tracker/templates/configmap.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
- vrt
- update vrt to 5.0
- fixes #
- .
> update vrt to 5.0

- .github/workflows/ci.yaml
- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/files/seed.ts
- charts/visual-regression-tracker/templates/_helpers.tpl
- charts/visual-regression-tracker/templates/secrets.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
- vrt
- add support of custom seed.ts
- fixes #
- .
> vrt - add seed support

- charts/mysqldump/Chart.yaml
> update mysqldump chart

- .github/ct.yaml
- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/README.md
- charts/visual-regression-tracker/templates/_helpers.tpl
- charts/visual-regression-tracker/templates/auth-proxy-configmap.yaml
- charts/visual-regression-tracker/templates/auth-proxy-deployment.yaml
- charts/visual-regression-tracker/templates/auth-proxy-ingress.yaml
- charts/visual-regression-tracker/templates/auth-proxy-secret.yaml
- charts/visual-regression-tracker/templates/auth-proxy-service.yaml
- charts/visual-regression-tracker/templates/configmap.yaml
- charts/visual-regression-tracker/templates/ingress-ui.yaml
- charts/visual-regression-tracker/templates/secrets.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
- charts/visual-regression-tracker/values.yaml
- vrt
- add basic auth proxy to api
- fixes #
- .
> [vrt ]add basic auth proxy to api

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/auth-proxy-deployment.yaml
- charts/visual-regression-tracker/templates/auth-proxy-pdb.yaml
- charts/visual-regression-tracker/values.yaml
- vrt
- add pdb & tsc
- fixes #
- .
> [vrt] add pdb & tsc

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/templates/statefulset.yaml
> [vrt] add env vars again

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/sync-readme.yaml
- charts/mysqldump/Chart.yaml
- charts/mysqldump/values.yaml
- mysqldump
- use kokuwa image
- update ci
- fixes #
- .
> mysqldump - switch to kokuwa docker image

- .github/workflows/ci.yaml
- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- charts/fluentd-elasticsearch/values.yaml
- fluentd-elasticsearch
- change fluentd docker repo & update image
- fixes #
- .
> change fluentd docker repo

- charts/visual-regression-tracker/Chart.yaml
- charts/visual-regression-tracker/values.yaml
- .
- update vrt to 5.0.11
- fixes #
- .
> update vrt to 5.0.11

- charts/nginx-php-fpm/.helmignore
- charts/nginx-php-fpm/Chart.yaml
- charts/nginx-php-fpm/README.md
- charts/nginx-php-fpm/templates/NOTES.txt
- charts/nginx-php-fpm/templates/_helpers.tpl
- charts/nginx-php-fpm/templates/configmap-nginx.yaml
- charts/nginx-php-fpm/templates/configmap-php.yaml
- charts/nginx-php-fpm/templates/deployment-nginx.yaml
- charts/nginx-php-fpm/templates/deployment-php.yaml
- charts/nginx-php-fpm/templates/hpa-nginx.yaml
- charts/nginx-php-fpm/templates/hpa-php.yaml
- charts/nginx-php-fpm/templates/ingress.yaml
- charts/nginx-php-fpm/templates/service-nginx.yaml
- charts/nginx-php-fpm/templates/service-php.yaml
- charts/nginx-php-fpm/templates/serviceaccount.yaml
- charts/nginx-php-fpm/values.yaml
- add nginx-php-fpm chart
- new chart
- fixes #
- .
> add nginx-php-fpm chart

- charts/mysqldump/Chart.yaml
- charts/mysqldump/templates/configmap-script.yaml
- mysqldump
- remove test connections from script (fails anyway)
- move housekeeping to the end so nothing is deleted if backups fails
- fixes #
- .
> mysqldump Update configmap-script.yaml

- charts/nginx-php-fpm/Chart.yaml
> nginx-fpm update

- charts/fluentd-elasticsearch/Chart.yaml
- charts/fluentd-elasticsearch/README.md
- fluentd-elasticsearch
- deprecate chart
- it's not maintained anymore and there are alternatives like: https://github.com/bitnami/charts/tree/main/bitnami/fluentd
- fixes #
- .
> fluentd-elasticsearch - deprecate chart
